docker compose script

diff --git a/.github/workflows/ci_prod.yml b/.github/workflows/ci_prod.yml
--- a/.github/workflows/ci_prod.yml
+++ b/.github/workflows/ci_prod.yml
@@ -45,6 +45,23 @@ jobs:
           username: ${{ secrets.EC2_USER }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           script: |
+            # Check for Docker and install if not found
+            if ! command -v docker &> /dev/null
+            then
+                echo "Docker not found, installing..."
+                sudo apt-get update
+                sudo apt-get install docker.io -y
+                sudo usermod -aG docker $USER
+            fi
+
+            # Check for Docker Compose and install if not found
+            if ! command -v docker-compose &> /dev/null
+            then
+                echo "Docker Compose not found, installing..."
+                sudo apt-get update
+                sudo apt-get install docker-compose-plugin -y
+            fi
+
             # Check if the directory exists. If not, clone the repository.
             if [ ! -d "/home/${{ secrets.EC2_USER }}/outfique" ]; then
               cd /home/${{ secrets.EC2_USER }}
@@ -58,10 +75,10 @@ jobs:
             git pull origin main
 
             # Pull the latest Docker image
-            sudo docker-compose pull
+            sudo docker compose pull
 
             # Stop and remove old containers
-            sudo docker-compose down --remove-orphans
+            sudo docker compose down --remove-orphans
 
             # Start new containers
-            sudo docker-compose up -d
+            sudo docker compose up -d
